import 'dart:io';

import 'package:claude_sdk/claude_sdk.dart';
import 'package:path/path.dart' as p;

/// Writes a temporary `.codex/config.toml` in the working directory
/// so that `codex exec` discovers our MCP servers.
///
/// Codex CLI reads MCP server configuration from its config file.
/// Each server is registered as a `[mcp_servers.<name>]` section
/// with the `url` pointing to our running [McpServerBase] instances.
///
/// If a user config already exists, it is backed up and restored
/// when [cleanUp] is called.
class CodexMcpRegistry {
  /// Stores original config content for restoration on cleanup.
  /// A `null` value means the file did not exist before we wrote it.
  static final Map<String, String?> _backups = {};

  /// Write `.codex/config.toml` with MCP server entries.
  ///
  /// If the file already exists, it is backed up first and will be
  /// restored when [cleanUp] is called.
  static Future<void> writeConfig({
    required List<McpServerBase> mcpServers,
    required String workingDirectory,
  }) async {
    if (mcpServers.isEmpty) return;

    final configDir = Directory(p.join(workingDirectory, '.codex'));
    if (!configDir.existsSync()) {
      configDir.createSync(recursive: true);
    }

    final configFile = File(p.join(configDir.path, 'config.toml'));

    // Backup existing config
    if (configFile.existsSync()) {
      _backups[workingDirectory] = await configFile.readAsString();
    } else {
      _backups[workingDirectory] = null;
    }

    final buffer = StringBuffer();
    buffer.writeln('# Auto-generated by codex_sdk — do not edit manually');
    buffer.writeln(
      '# Original config backed up and will be restored on cleanup',
    );
    buffer.writeln();

    for (final server in mcpServers) {
      if (!server.isRunning) continue;

      final config = server.toClaudeConfig();
      final url = config['url'] as String;

      buffer.writeln('[mcp_servers.${_sanitizeName(server.name)}]');
      buffer.writeln('url = "$url"');
      buffer.writeln();
    }

    await configFile.writeAsString(buffer.toString());
  }

  /// Restore the original config file, or remove the generated one.
  static Future<void> cleanUp({required String workingDirectory}) async {
    final configFile = File(p.join(workingDirectory, '.codex', 'config.toml'));
    final backup = _backups.remove(workingDirectory);

    if (backup != null) {
      // Restore original config
      await configFile.writeAsString(backup);
    } else if (configFile.existsSync()) {
      // No backup means we created the file — safe to delete
      await configFile.delete();
    }
  }

  /// Sanitize server name for use as a TOML key.
  /// Replaces non-alphanumeric characters with underscores.
  static String _sanitizeName(String name) {
    return name.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
  }
}
