import 'dart:io';

import 'package:claude_sdk/claude_sdk.dart';
import 'package:path/path.dart' as p;

/// Writes a temporary `.codex/config.toml` in the working directory
/// so that `codex exec` discovers our MCP servers.
///
/// Codex CLI reads MCP server configuration from its config file.
/// Each server is registered as a `[mcp_servers.<name>]` section
/// with the `url` pointing to our running [McpServerBase] instances.
class CodexMcpRegistry {
  /// Write `.codex/config.toml` with MCP server entries.
  ///
  /// If the file already exists, it is overwritten. The file is written
  /// to `<workingDirectory>/.codex/config.toml`.
  static Future<void> writeConfig({
    required List<McpServerBase> mcpServers,
    required String workingDirectory,
  }) async {
    if (mcpServers.isEmpty) return;

    final configDir = Directory(p.join(workingDirectory, '.codex'));
    if (!configDir.existsSync()) {
      configDir.createSync(recursive: true);
    }

    final buffer = StringBuffer();
    buffer.writeln('# Auto-generated by codex_sdk — do not edit manually');
    buffer.writeln();

    for (final server in mcpServers) {
      if (!server.isRunning) continue;

      final config = server.toClaudeConfig();
      final url = config['url'] as String;

      buffer.writeln('[mcp_servers.${_sanitizeName(server.name)}]');
      buffer.writeln('url = "$url"');
      buffer.writeln();
    }

    final configFile = File(p.join(configDir.path, 'config.toml'));
    await configFile.writeAsString(buffer.toString());
  }

  /// Remove the generated config file.
  static Future<void> cleanUp({required String workingDirectory}) async {
    final configFile = File(p.join(workingDirectory, '.codex', 'config.toml'));
    if (configFile.existsSync()) {
      await configFile.delete();
    }
  }

  /// Sanitize server name for use as a TOML key.
  /// Replaces non-alphanumeric characters with underscores.
  static String _sanitizeName(String name) {
    return name.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
  }
}
