// Tool to generate bundled team framework assets for compiled binaries.
//
// When dart compiles to a native executable, package assets are not included.
// This script reads all .md files from assets/team_framework/ and generates
// a Dart file with the content embedded as string constants.
//
// Usage: dart run packages/vide_core/tool/generate_bundled_team_framework.dart
// (Run from repo root)

import 'dart:io';
import 'package:path/path.dart' as path;

void main() async {
  // Determine paths based on script location or cwd
  final cwd = Directory.current.path;
  String videCorePath;

  if (cwd.endsWith('packages/vide_core')) {
    videCorePath = cwd;
  } else if (Directory(path.join(cwd, 'packages', 'vide_core')).existsSync()) {
    videCorePath = path.join(cwd, 'packages', 'vide_core');
  } else {
    print('Error: Could not locate packages/vide_core directory.');
    print('Run from repo root or packages/vide_core directory.');
    exit(1);
  }

  final assetsPath = path.join(videCorePath, 'assets', 'team_framework');
  final outputPath = path.join(
    videCorePath,
    'lib',
    'src',
    'generated',
    'bundled_team_framework.dart',
  );

  // Verify assets directory exists
  if (!Directory(assetsPath).existsSync()) {
    print('Error: Assets directory not found at: $assetsPath');
    exit(1);
  }

  print('Reading team framework assets from: $assetsPath');
  print('Will write output to: $outputPath');

  // Read all assets by category
  final bundledAssets = <String, Map<String, String>>{};

  for (final category in ['teams', 'agents', 'etiquette', 'behaviors']) {
    final categoryDir = Directory(path.join(assetsPath, category));
    if (!categoryDir.existsSync()) {
      print('Warning: Category directory not found: ${categoryDir.path}');
      continue;
    }

    bundledAssets[category] = {};

    final files = categoryDir.listSync().whereType<File>().where(
      (f) => f.path.endsWith('.md'),
    );

    for (final file in files) {
      final fileName = path.basenameWithoutExtension(file.path);
      final content = await file.readAsString();
      bundledAssets[category]![fileName] = content;
      print('  Loaded: $category/$fileName.md');
    }
  }

  // Generate output
  final output = _generateOutput(bundledAssets);

  // Ensure output directory exists
  final outputDir = Directory(path.dirname(outputPath));
  if (!outputDir.existsSync()) {
    await outputDir.create(recursive: true);
  }

  // Write output file
  await File(outputPath).writeAsString(output);
  print('\nGenerated: $outputPath');
  print('Done!');
}

String _generateOutput(Map<String, Map<String, String>> bundledAssets) {
  final buffer = StringBuffer();

  // Header
  buffer.writeln('// GENERATED FILE - DO NOT EDIT');
  buffer.writeln(
    '// Generated by: dart run packages/vide_core/tool/generate_bundled_team_framework.dart',
  );
  buffer.writeln('// Source: packages/vide_core/assets/team_framework/');
  buffer.writeln('//');
  buffer.writeln(
    '// This file contains team framework assets embedded as strings for',
  );
  buffer.writeln(
    '// compiled binaries that cannot access package assets at runtime.',
  );
  buffer.writeln();

  // Generate constants for each category
  for (final category in ['teams', 'agents', 'etiquette', 'behaviors']) {
    final assets = bundledAssets[category] ?? {};

    buffer.writeln('/// Bundled $category assets.');
    buffer.writeln('const bundled${_capitalize(category)} = <String, String>{');

    for (final entry in assets.entries) {
      final name = entry.key;
      final content = entry.value;

      // Escape the content for use in a raw string
      // Raw strings can't contain the delimiter, so we check for that
      final escapedContent = _escapeForRawString(content);

      buffer.writeln("  '$name': r'''");
      buffer.writeln(escapedContent);
      buffer.writeln("''',");
    }

    buffer.writeln('};');
    buffer.writeln();
  }

  // Generate a combined accessor
  buffer.writeln('/// All bundled team framework assets by category.');
  buffer.writeln('const bundledTeamFramework = <String, Map<String, String>>{');
  buffer.writeln("  'teams': bundledTeams,");
  buffer.writeln("  'agents': bundledAgents,");
  buffer.writeln("  'etiquette': bundledEtiquette,");
  buffer.writeln("  'behaviors': bundledBehaviors,");
  buffer.writeln('};');

  return buffer.toString();
}

String _capitalize(String s) {
  if (s.isEmpty) return s;
  return s[0].toUpperCase() + s.substring(1);
}

String _escapeForRawString(String content) {
  // Raw strings can't contain the delimiter '''
  // If content contains ''', replace with a safe alternative
  if (content.contains("'''")) {
    // Replace ''' with escaped version - we'll use a workaround
    // by closing and reopening the raw string
    content = content.replaceAll("'''", "''' r\"'''\" r'''");
  }
  return content;
}
